"""Writes a Blender import script alongside the reconstruction.

Answering the obvious question directly: this pipeline does **not** emit a
`.blend`. Producing one requires Blender itself to be running, since the format
is only written by Blender's own Python API. What it emits instead is
`open_in_blender.py` — run it inside Blender and the scene assembles itself.

Blender opens `points.ply` natively (File > Import > PLY), so you can always
skip the script. Two things the script does that a bare import does not:

  * **Rotates the scene upright.** Blender is Z-up; reconstruction models
    generally emit Y-up. A raw import leaves your room lying on its side, which
    reads as a broken reconstruction rather than an axis convention.
  * **Makes the points visible.** A vertices-only mesh renders as nothing in
    EEVEE and Cycles — geometry with no faces has no surface to shade. The
    script adds a Geometry Nodes tree that converts vertices to renderable
    points and wires the imported colour attribute into a material.

The 3DGS `scene.ply` is a different matter: Blender cannot read Gaussian splats
without an add-on (KIRI's 3DGS Render). Use `points.ply` for the native path.
"""

from __future__ import annotations

import os

TEMPLATE = '''"""Auto-generated by glasses3d. Run inside Blender:

    Blender > Scripting tab > Open > this file > Run Script

or headless:

    blender --background --python open_in_blender.py --save-as scene.blend
"""

import bpy
import math
import os
import sys

PLY = r"{ply}"
UP_AXIS = "{up_axis}"          # source convention: "Y" or "Z"
POINT_RADIUS = {radius}

if not os.path.exists(PLY):
    raise SystemExit("point cloud not found: " + PLY)


def fresh_scene():
    """Empty the default cube/light/camera so the import is not buried."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)


def import_ply(path):
    """Blender renamed the PLY operator in 4.0; support both."""
    if hasattr(bpy.ops.wm, "ply_import"):
        bpy.ops.wm.ply_import(filepath=path)
    else:
        bpy.ops.import_mesh.ply(filepath=path)
    obj = bpy.context.selected_objects[0] if bpy.context.selected_objects \\
        else bpy.context.view_layer.objects.active
    if obj is None:
        raise SystemExit("import produced no object")
    return obj


def find_color_attribute(mesh):
    """Locate the imported colour layer, whatever Blender decided to call it.

    The PLY importer has used 'Col', 'Color' and mesh.color_attributes across
    versions. Guessing one name and silently rendering grey is the common
    failure here, so check what actually arrived.
    """
    if getattr(mesh, "color_attributes", None) and len(mesh.color_attributes):
        return mesh.color_attributes[0].name
    for layer in getattr(mesh, "vertex_colors", []):
        return layer.name
    return None


def point_material(color_attr):
    mat = bpy.data.materials.new("glasses3d_points")
    mat.use_nodes = True
    nodes, links = mat.node_tree.nodes, mat.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    if bsdf is None:
        bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    if color_attr:
        attr = nodes.new("ShaderNodeAttribute")
        attr.attribute_name = color_attr
        attr.location = (-320, 0)
        links.new(attr.outputs["Color"], bsdf.inputs["Base Color"])
    # Reconstructed colour already contains the scene's lighting. Re-lighting it
    # double-counts illumination, so drive emission and leave it unlit.
    if "Emission Color" in bsdf.inputs and color_attr:
        links.new(attr.outputs["Color"], bsdf.inputs["Emission Color"])
        bsdf.inputs["Emission Strength"].default_value = 1.0
    bsdf.inputs["Roughness"].default_value = 1.0
    return mat


def as_points(obj, mat, radius):
    """Geometry Nodes: vertices -> renderable points.

    Without this the object is invisible in render engines: a mesh with no
    faces has no surface, so there is nothing to shade.
    """
    mod = obj.modifiers.new("glasses3d_points", "NODES")
    tree = bpy.data.node_groups.new("glasses3d_points", "GeometryNodeTree")
    mod.node_group = tree

    if hasattr(tree, "interface"):          # Blender 4.x
        tree.interface.new_socket("Geometry", in_out="INPUT", socket_type="NodeSocketGeometry")
        tree.interface.new_socket("Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry")
    else:                                    # Blender 3.x
        tree.inputs.new("NodeSocketGeometry", "Geometry")
        tree.outputs.new("NodeSocketGeometry", "Geometry")

    nodes, links = tree.nodes, tree.links
    n_in = nodes.new("NodeGroupInput"); n_in.location = (-400, 0)
    n_out = nodes.new("NodeGroupOutput"); n_out.location = (400, 0)
    to_points = nodes.new("GeometryNodeMeshToPoints"); to_points.location = (-150, 0)
    to_points.inputs["Radius"].default_value = radius
    set_mat = nodes.new("GeometryNodeSetMaterial"); set_mat.location = (150, 0)
    set_mat.inputs["Material"].default_value = mat

    links.new(n_in.outputs[0], to_points.inputs["Mesh"])
    links.new(to_points.outputs["Points"], set_mat.inputs["Geometry"])
    links.new(set_mat.outputs["Geometry"], n_out.inputs[0])


def main():
    fresh_scene()
    obj = import_ply(PLY)
    obj.name = "world"

    if UP_AXIS.upper() == "Y":
        # Blender is Z-up; most reconstruction models emit Y-up. Skipping this
        # leaves the room on its side, which looks like a broken reconstruction
        # rather than a convention mismatch.
        obj.rotation_euler[0] = math.radians(90)

    color_attr = find_color_attribute(obj.data)
    print("glasses3d: %d vertices, colour attribute: %s"
          % (len(obj.data.vertices), color_attr or "NONE (will render grey)"))

    as_points(obj, point_material(color_attr), POINT_RADIUS)

    # Frame it, and switch the viewport to rendered shading so the points are
    # actually visible without hunting through menus.
    for area in bpy.context.screen.areas if bpy.context.screen else []:
        if area.type == "VIEW_3D":
            area.spaces[0].shading.type = "MATERIAL"
            for region in area.regions:
                if region.type == "WINDOW":
                    with bpy.context.temp_override(area=area, region=region):
                        bpy.ops.object.select_all(action="DESELECT")
                        obj.select_set(True)
                        bpy.ops.view3d.view_selected()

    if "--save-as" in sys.argv:
        out = sys.argv[sys.argv.index("--save-as") + 1]
        bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath(out))
        print("glasses3d: saved " + out)


main()
'''


def write_blender_script(out_dir: str, ply_name: str = "points.ply",
                         up_axis: str = "Y", radius: float = 0.01) -> str:
    """Emit `open_in_blender.py` next to the reconstruction."""
    path = os.path.join(out_dir, "open_in_blender.py")
    os.makedirs(out_dir, exist_ok=True)
    with open(path, "w") as fh:
        fh.write(TEMPLATE.format(
            ply=os.path.abspath(os.path.join(out_dir, ply_name)),
            up_axis=up_axis, radius=radius))
    return path


README = """# Your reconstructed world

## Walk through it (easiest)

Open `walkthrough.html` in a browser and drop `points.ply` onto it.

    W A S D   move          mouse   look
    shift     sprint        space/C up, down
    V         1st/3rd person
    U         cycle up-axis (if the world is on its side)
    [ ]       point size    R  reset    esc  release cursor

Nothing is uploaded; the file is parsed in the tab.

## Blender

`points.ply` imports natively: File > Import > Stanford PLY. But a bare import
lands sideways (Blender is Z-up, the reconstruction is Y-up) and renders as
nothing (a vertices-only mesh has no surface to shade).

So instead: Blender > Scripting > Open > `open_in_blender.py` > Run Script.
That rotates it upright, converts the vertices to renderable points, and wires
the colours into a material.

Headless, to get an actual .blend file:

    blender --background --python open_in_blender.py --save-as world.blend

## Web viewer / other tools

`scene.ply` is 3D Gaussian Splats. Drag it onto https://superspl.at/editor.
For Blender it needs the KIRI 3DGS Render add-on; `points.ply` is the native path.

## Files

    points.ply          coloured point cloud - the portable one
    scene.ply           3D Gaussian Splats - better looking, needs splat support
    scene.json          scene graph (background + tracked objects)
    meta.json           what produced this
    walkthrough.html    self-contained viewer
    open_in_blender.py  Blender setup script
"""


def write_output_readme(out_dir: str) -> str:
    path = os.path.join(out_dir, "README.md")
    with open(path, "w") as fh:
        fh.write(README)
    return path
