"""M5: write reconstruction artifacts that every downstream target can read.

Two PLY flavours:

    point cloud   x,y,z + rgb. Universally readable; good for sanity checks.
    3D Gaussians  the INRIA 3DGS layout that SuperSplat, the KIRI Blender
                  addon, UnityGaussianSplatting and the Unreal SplatRenderer
                  all consume.

Plus `bake_scene`, which flattens the dynamic scene graph — background plus
posed objects — into one splat cloud for viewers that have no notion of a scene
graph.

Baking a transformed Gaussian is not just moving its centre. A Gaussian carries
an orientation (a quaternion) as well as a position, and rotating the object
must rotate both. Translating the means alone leaves every Gaussian's ellipsoid
pointing the way it did before the object turned, which shows up as smeared,
subtly wrong-looking geometry rather than an obvious error.
"""

from __future__ import annotations

import json
import os
import struct
from typing import Dict, Iterable, List, Optional, Sequence

import numpy as np

# Spherical-harmonic DC coefficient <-> linear colour. The 3DGS convention
# stores colour as SH degree 0, and viewers apply this constant on load; writing
# raw RGB here produces a washed-out splat that looks like a tone-mapping bug.
SH_C0 = 0.28209479177387814


def _ply_header(count: int, props: Sequence[tuple], comments: Iterable[str] = ()) -> bytes:
    lines = ["ply", "format binary_little_endian 1.0"]
    lines += ["comment %s" % c for c in comments]
    lines.append("element vertex %d" % count)
    lines += ["property %s %s" % (t, n) for t, n in props]
    lines.append("end_header")
    return ("\n".join(lines) + "\n").encode("ascii")


def write_point_cloud(path: str, xyz: np.ndarray,
                      rgb: Optional[np.ndarray] = None) -> str:
    """Write an x,y,z(,r,g,b) binary PLY."""
    xyz = np.asarray(xyz, dtype=np.float32).reshape(-1, 3)
    props = [("float", "x"), ("float", "y"), ("float", "z")]
    if rgb is not None:
        rgb = np.asarray(rgb).reshape(-1, 3)
        if rgb.dtype != np.uint8:  # accept 0..1 floats too
            rgb = np.clip(rgb * 255.0, 0, 255).astype(np.uint8)
        props += [("uchar", "red"), ("uchar", "green"), ("uchar", "blue")]

    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(_ply_header(len(xyz), props, ["generated by glasses3d"]))
        if rgb is None:
            fh.write(xyz.astype("<f4").tobytes())
        else:
            rec = np.empty(len(xyz), dtype=[("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
                                            ("red", "u1"), ("green", "u1"), ("blue", "u1")])
            rec["x"], rec["y"], rec["z"] = xyz[:, 0], xyz[:, 1], xyz[:, 2]
            rec["red"], rec["green"], rec["blue"] = rgb[:, 0], rgb[:, 1], rgb[:, 2]
            fh.write(rec.tobytes())
    return path


class Splats:
    """A 3D Gaussian cloud in the INRIA PLY convention.

    means      (N,3) centres, world space
    scales     (N,3) LOG-space axis lengths — the format stores log(sigma)
    rots       (N,4) orientation quaternions, (w,x,y,z)
    opacities  (N,)  LOGIT-space alpha — the format stores the pre-sigmoid value
    sh_dc      (N,3) SH degree-0 colour

    The log/logit storage is not incidental: it lets the optimiser work in an
    unconstrained space during training. Writing raw sigmas or alphas produces a
    file that loads without complaint and renders as a fog of enormous, fully
    opaque blobs.
    """

    def __init__(self, means, scales, rots, opacities, sh_dc):
        self.means = np.asarray(means, dtype=np.float32).reshape(-1, 3)
        n = len(self.means)
        self.scales = np.asarray(scales, dtype=np.float32).reshape(n, 3)
        self.rots = np.asarray(rots, dtype=np.float32).reshape(n, 4)
        self.opacities = np.asarray(opacities, dtype=np.float32).reshape(n)
        self.sh_dc = np.asarray(sh_dc, dtype=np.float32).reshape(n, 3)

    def __len__(self) -> int:
        return len(self.means)

    @classmethod
    def from_points(cls, xyz, rgb, radius: float = 0.01, alpha: float = 0.85) -> "Splats":
        """Build an isotropic splat cloud from a coloured point cloud."""
        xyz = np.asarray(xyz, dtype=np.float32).reshape(-1, 3)
        n = len(xyz)
        rgb = np.asarray(rgb, dtype=np.float32).reshape(n, 3)
        if rgb.max() > 1.0:
            rgb = rgb / 255.0
        rots = np.tile(np.array([1.0, 0.0, 0.0, 0.0], np.float32), (n, 1))
        return cls(
            means=xyz,
            scales=np.full((n, 3), np.log(radius), np.float32),
            rots=rots,
            opacities=np.full(n, float(np.log(alpha / (1.0 - alpha))), np.float32),
            sh_dc=(rgb - 0.5) / SH_C0,
        )

    def concat(self, other: "Splats") -> "Splats":
        return Splats(
            np.vstack([self.means, other.means]),
            np.vstack([self.scales, other.scales]),
            np.vstack([self.rots, other.rots]),
            np.concatenate([self.opacities, other.opacities]),
            np.vstack([self.sh_dc, other.sh_dc]),
        )

    def transformed(self, T: np.ndarray) -> "Splats":
        """Apply a 4x4 rigid transform to the whole cloud.

        Rotates means *and* orientations. Scales and opacities are invariant
        under a rigid transform, so they carry over untouched.
        """
        T = np.asarray(T, dtype=np.float64).reshape(4, 4)
        R, t = T[:3, :3], T[:3, 3]
        means = (self.means @ R.T) + t
        return Splats(means, self.scales,
                      _quat_mul(_mat_to_quat(R), self.rots),
                      self.opacities, self.sh_dc)


def _mat_to_quat(R: np.ndarray) -> np.ndarray:
    """3x3 rotation -> (w,x,y,z), via the numerically stable branch selection.

    Picking the branch with the largest denominator matters: the naive
    trace-only formula divides by a quantity approaching zero for rotations near
    180 degrees, and silently loses precision well before it blows up.
    """
    m = np.asarray(R, dtype=np.float64)
    tr = np.trace(m)
    if tr > 0:
        s = math_sqrt(tr + 1.0) * 2
        return np.array([0.25 * s, (m[2, 1] - m[1, 2]) / s,
                         (m[0, 2] - m[2, 0]) / s, (m[1, 0] - m[0, 1]) / s])
    i = int(np.argmax([m[0, 0], m[1, 1], m[2, 2]]))
    j, k = (i + 1) % 3, (i + 2) % 3
    s = math_sqrt(m[i, i] - m[j, j] - m[k, k] + 1.0) * 2
    q = np.zeros(4)
    q[0] = (m[k, j] - m[j, k]) / s
    q[i + 1] = 0.25 * s
    q[j + 1] = (m[j, i] + m[i, j]) / s
    q[k + 1] = (m[k, i] + m[i, k]) / s
    return q


def math_sqrt(x: float) -> float:
    return float(np.sqrt(max(x, 1e-20)))


def _quat_mul(q: np.ndarray, rest: np.ndarray) -> np.ndarray:
    """Hamilton product q * rest, broadcasting q over an (N,4) array."""
    w0, x0, y0, z0 = q
    w1, x1, y1, z1 = rest[:, 0], rest[:, 1], rest[:, 2], rest[:, 3]
    out = np.empty_like(rest)
    out[:, 0] = w0 * w1 - x0 * x1 - y0 * y1 - z0 * z1
    out[:, 1] = w0 * x1 + x0 * w1 + y0 * z1 - z0 * y1
    out[:, 2] = w0 * y1 - x0 * z1 + y0 * w1 + z0 * x1
    out[:, 3] = w0 * z1 + x0 * y1 - y0 * x1 + z0 * w1
    return out


SPLAT_PROPS = ([("float", n) for n in ("x", "y", "z", "nx", "ny", "nz")]
               + [("float", "f_dc_%d" % i) for i in range(3)]
               + [("float", "opacity")]
               + [("float", "scale_%d" % i) for i in range(3)]
               + [("float", "rot_%d" % i) for i in range(4)])


def write_splats(path: str, splats: Splats) -> str:
    """Write SH degree-0 3DGS PLY. Readable by SuperSplat, Blender, Unity, UE."""
    n = len(splats)
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    data = np.zeros((n, 14), dtype="<f4")
    data[:, 0:3] = splats.means
    # nx,ny,nz stay zero — the format keeps the fields but 3DGS ignores normals.
    data[:, 6:9] = splats.sh_dc
    data[:, 9] = splats.opacities
    data[:, 10:13] = splats.scales
    # rot_0..3 is (w,x,y,z), matching the training code's quaternion order.
    with open(path, "wb") as fh:
        fh.write(_ply_header(n, SPLAT_PROPS, ["generated by glasses3d"]))
        full = np.hstack([data[:, :13], splats.rots.astype("<f4")])
        fh.write(np.ascontiguousarray(full, dtype="<f4").tobytes())
    return path


def bake_scene(background: Optional[Splats], objects: Sequence[tuple]) -> Splats:
    """Flatten background + [(Splats, 4x4 pose)] into one cloud.

    Each object's geometry is stored in its own local frame, so baking applies
    its current pose. Re-baking after something moves is what a scene-graph-less
    viewer needs; viewers that understand the graph should consume
    `scene_graph()` and move a transform node instead — far cheaper.
    """
    out = background
    for splats, pose in objects:
        posed = splats.transformed(pose)
        out = posed if out is None else out.concat(posed)
    return out if out is not None else Splats(
        np.zeros((0, 3)), np.zeros((0, 3)), np.zeros((0, 4)),
        np.zeros(0), np.zeros((0, 3)))


def write_scene_graph(path: str, graph: dict) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w") as fh:
        json.dump(graph, fh, indent=2)
    return path


def read_ply_header(path: str) -> dict:
    """Minimal reader, used by the tests to verify what was written."""
    props: List[str] = []
    count = 0
    with open(path, "rb") as fh:
        if fh.readline().strip() != b"ply":
            raise ValueError("not a PLY file")
        fmt = ""
        while True:
            line = fh.readline().decode("ascii").strip()
            if line.startswith("format"):
                fmt = line.split()[1]
            elif line.startswith("element vertex"):
                count = int(line.split()[-1])
            elif line.startswith("property"):
                props.append(line.split()[-1])
            elif line == "end_header":
                break
            elif not line:
                raise ValueError("unterminated header")
        return {"format": fmt, "count": count, "properties": props,
                "data_offset": fh.tell()}
